apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: 'eureka-server'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['eureka-server:8761']
