apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-server-config
data:
  application.properties: |
    server.port=8761
    eureka.client.register-with-eureka=false
    eureka.client.fetch-registry=false
    eureka.instance.hostname=eureka-server
    management.endpoints.web.exposure.include=health,info,metrics,prometheus