apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
bases:
  - ../../base
configMapGenerator:
  - name: eureka-server-config
    behavior: merge
    literals:
      - ENVIRONMENT=prod